=== anjijava16/java-primer/trunk/xcapinterface/doc/xml/contacts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="contacts" xmlns="contacts"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="contacts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contact" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element ref="list" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contact" maxOccurs="unbounded"
					minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<!-- <xs:attribute name="source" use="required" type="xs:string"></xs:attribute> -->
		</xs:complexType>
	</xs:element>

	<xs:element name="contact">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="method" type="xs:string" maxOccurs="1" minOccurs="1"/>
				<xs:element name="contactName" type="xs:string" maxOccurs="1" minOccurs="1"/>
				<xs:element name="createDate" type="xs:string" maxOccurs="1" minOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== anjijava16/java-primer/trunk/xcapinterface/doc/xml/example-new-contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="contacts contacts.xsd">
	<contact id="11024">
		<method>13510776271</method>
		<contactName>Gykoooooo</contactName>		
		<createDate>2011-09-28 07:10:20</createDate>
	</contact>

	<contact id="1046">
		<method>84236457</method>
		<contactName>翟小斌</contactName>		
		<createDate>2011-09-28 07:10:20</createDate>
	</contact>

	<list id="friends@facebook">
		<contact id="11034">
			<method>46546464646</method>
			<contactName>yuankang</contactName>			
			<createDate>2011-09-28 07:10:20</createDate>
		</contact>
		<contact id="11032">
			<method>156445564641</method>
			<contactName>yuankang</contactName>			
			<createDate>2011-09-28 07:10:20</createDate>
		</contact>
	</list>
</contacts>

=== anjijava16/java-primer/trunk/xcapinterface/doc/xml/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns="contact-lists"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="contacts contacts.xsd">
	
	<contact id="890">
		<method>13823514039</method>
		<contactName>杨威</contactName>		
		<createDate>2011-09-27 05:26:52</createDate>
	</contact>
	<contact id="891">
		<method>13823514031</method>
		<contactName>abc</contactName>		
		<createDate>2011-09-27 05:26:52</createDate>
	</contact>
	<list id="friends@facebook">
		<contact id="1892">
			<method>13823514031</method>
			<contactName>abc</contactName>			
			<createDate>2011-09-27 05:26:52</createDate>
		</contact>
		<contact id="1893">
			<method>13823514031</method>
			<contactName>abc</contactName>			
			<createDate>2011-09-27 05:26:52</createDate>
		</contact>
	</list>
	<list id="close-friends@facebook">
		<contact id="1894">
			<method>13823514031</method>
			<contactName>abc</contactName>			
			<createDate>2011-09-27 05:26:52</createDate>
		</contact>
		<contact id="1895">
			<method>13823514031</method>
			<contactName>abc</contactName>			
			<createDate>2011-09-27 05:26:52</createDate>
		</contact>
	</list>
</contacts>

=== anjijava16/java-primer/trunk/xcapinterface/test/http/contacts/xml/example-new-contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="contacts contacts.xsd">
	<contact method="13510776272">
		<contactName>Gykooooox</contactName>
	</contact>
	<contact method="84236457">
		<contactName>翟小斌</contactName>
	</contact>
	<contact method="46546464646">
		<contactName>yuankang</contactName>
	</contact>
	<contact method="156445564641">
		<contactName>yuanka</contactName>
	</contact>
</contacts>
