=== anjijava16/java-primer/trunk/xcapinterface/src/doc/contact-list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.slieer.com/abc" 
	xmlns="http://www.slieer.com/abc"
	elementFormDefault="qualified">

	<xs:element name="contact-lists">
		<xs:complexType>
			<xs:sequence minOccurs="1">
				<xs:element name="contact" type="contact-type" minOccurs="0" />
				<xs:element name="list" type="list-type" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="contact-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="msisdn" type="xs:string" />

	</xs:complexType>

	<xs:complexType name="list-type">
			<xs:complexContent>
				<xs:extension base="contact-type">
				</xs:extension>
			</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== anjijava16/java-primer/trunk/xcapinterface/doc/exam.xml
<?xml version="1.0" encoding="UTF-8"?>
<contact-lists
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.slieer.com/abc contact-list.xsd">
	
	<ab></ab>
	<contact msisdn=" 13823322278">
		<name>Bill Doe</name>
	</contact>
	<list name="friends">
		<contact msisdn="joe@example.com">
			<name>Joe Smith</name>
		</contact>
		<contact msisdn="nancy@example.com">
			<name>Nancy Gross</name>
		</contact>
	</list>
</contact-lists>
