=== anjijava16/java-primer/trunk/xcapinterface/doc/contact-list-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="contact-lists" xmlns="contact-lists"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="contact-lists">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contact" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element ref="list" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contact" maxOccurs="unbounded"
					minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<!-- <xs:attribute name="source" use="required" type="xs:string"></xs:attribute> -->
		</xs:complexType>
	</xs:element>

	<xs:element name="contact">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nickname" maxOccurs="1" minOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="nickname">
		<xs:simpleType>
			<xs:restriction base="xs:string"></xs:restriction>
		</xs:simpleType>
	</xs:element>

</xs:schema>

=== anjijava16/java-primer/trunk/xcapinterface/src/doc/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<contact-lists xmlns="contact-lists"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="contact-lists file:///E:/BorqsWorkspace/workspace/xcapinterface/src/doc/contact-list-1.xsd">
	<!--
	 xsi:schemaLocation="contact-lists file:///E:/BorqsWorkspace/MyGoogleCode/xcapinterface/src/doc/contact-list-1.xsd"  
	 -->
	<contact id="13823322278">
		<nickname>Bill Doe</nickname>
	</contact>
	<contact id="13823322271">
		<nickname>Bill Doe</nickname>
	</contact>
	<list id="friends@facebook">
		<contact id="13530039954">
			<nickname>Joe Smith</nickname>
		</contact>
		<contact id="8613530039954">
			<nickname>Nancy Gross</nickname>
		</contact>
	</list>
	<list id="close-friends@facebook">
		<contact id="joe">
			<nickname>Joe Smith</nickname>
		</contact>
		<contact id="cliff">
			<nickname>cliff Gross</nickname>
		</contact>
		<contact id="lily">
			<nickname>Nancy Gross</nickname>
		</contact>
	</list>
	<list id="close-friends@Twitter"></list>
</contact-lists>
